### ISSUE TITLE
Problem on buttons.pug

### ISSUE THREAD

**Issue by geezot** [mike-goodwin/pug-bootstrap#1]
Hi, 
There is a problem on buttons.pug in components, when you specify the caption for submit-primary,
like this 
`+submit-primary("CREATE")`
 you have the value equal to #{caption} and the class equal to btn-#{type}.
I tried to replace the code (line 135) : 
`input.btn(class="btn-#{type}",type="submit",value="#{caption}")`
by
`input.btn(class="btn-" + type,type="submit",value=caption)`
and now it works fine.
it the same thing on line 115 in the same file
cheers 
Fabrice

**Comment by mike-goodwin** [comment]
Thanks for raising this and sorry for the late response - I've been on holiday. would you be able to make a PR for this with your fix in it? No worries if you can't - just let me know either way.

**Comment by mike-goodwin** [comment]
Actually - it was pretty quick so I fixed it in cd42b5a3d0ab0a17aa0eec98df96ea0df03d96a8
