### ISSUE TITLE
Modal mixin doesn't work

### ISSUE THREAD

**Issue by isanjosgon** [mike-goodwin/pug-bootstrap#2]
The code

```
 button.btn.btn-primary(data-toggle="modal",data-target="#myModal") Launch demo modal
 +modal("Modal title","myModal")
	p This is modal content
```

doesn't work

**Comment by mike-goodwin** [comment]
Thanks for raising this issue and apologies for the slow reply.

The issue was that the modal mixin was not fixed up to use the new pug syntax for local variables - this is fixed in commit 10b5df6a94da141b946c1f46819a33097813ef60 and in the latest npm package (0.0.3)
