### ISSUE TITLE
not ready to use yet

### ISSUE THREAD

**Issue by shivshankar3578** [mike-goodwin/pug-bootstrap#29]
Hello guys 
i found this great work but seems not ready to use yet. i am newbie in javascript template engine. can i go with this and i'll update when official release.  i'll try my best contribution also.

**Comment by mike-goodwin** [comment]
Hello. Thank you for your interest! In terms of readiness for use I would make a couple of comments:

- From a quality perspective I stand behind the library. I've tried to build out the unit test coverage compared to the original Jade Bootstrap project and if there are bugs, please raise them and I'll try hard to get them fixed - or you could fix them with a PR :)
- From a completeness perspective, I have only ported the features that were in the original Jade Bootstrap project, plus a small number of enhancements. You are right though and I recognise that it is likely to be incomplete. If you come across any gaps, feel free to raise them as issues or submit PRs
- The underlying Pug project is not yet at a full release (current NPM version is 2.0.0-beta10). According to [their milestone](https://github.com/pugjs/pug/milestone/2) it is 95% complete. So as long as that is still not at full release it should be considered subject to some change.

Hope this helps!
